runtime: python312 # Ou a versão do Python que você está usando

entrypoint: gunicorn -b :$PORT setup.wsgi

handlers:
  # Esta configuração serve os arquivos estáticos diretamente pelo Google
  - url: /static
    static_dir: staticfiles/

  # Esta configuração direciona todas as outras requisições para a sua aplicação Django
  - url: /.*
    script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 1 # Comece com 1 para controlar custos

env_variables:
  SECRET_KEY: 'SUA_SECRET_KEY_VAI_AQUI' # Substitua em produção
  DATABASE_URL: 'postgres://USER:PASSWORD@/DBNAME?host=/cloudsql/PROJECT_ID:REGION:INSTANCE_NAME'
  GAE_APP_DOMAIN: 'seu-projeto.uc.r.appspot.com' # Substitua pelo domínio do seu app
